version: '3'

services:
  server:
    container_name: api-gateway-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - 8056:8056
    depends_on:
      - kafka
      - redis
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:5.2.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2184
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2184:2184

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.1
    depends_on:
      - zookeeper
    ports:
      - 9094:9092
      - 9997:9997
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2184
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9000:9000
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2184
      KAFKA_CLUSTERS_0_JMXPORT: 9997

  redis:
    container_name: redis
    image: redis:6
    ports:
      - 6379:6379
    environment:
      REDIS_PORT: 6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
